{
 "title": "Node utilization metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "query_result(kube_node_labels)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=\"/\",instance=\"$node\"}[10m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "sum(container_memory_usage_bytes{namespace!=\"\",instance=\"$node\"}) / SUM(kube_node_status_capacity_memory_bytes{node=\"$node\"})\n\n\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=\"$node\",namespace!=\"\"})/sum(kube_node_status_capacity{node=\"$node\",resource=\"memory\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( count(avg_over_time( kube_pod_container_resource_requests{container!=\"\",node=\"$node\"}[1h])) by (pod) * on (pod) group_right()sum(kube_pod_container_status_running) by (pod))"
    }
   ]
  },
  {
   "title": "Storage Capacity",
   "type": "stat",
   "description": "sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=\"$node\"})",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{id=\"/\",instance=\"$node\", device=\"/dev/nvme0n1p2\"})"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "RAM Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_capacity{node=\"$node\", resource=\"memory\", unit=\"byte\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "This panel shows historical utilization for the node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=\"/\",instance=\"$node\"}[10m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=\"$node\"}) / sum(kube_node_status_capacity_cpu_cores{node=\"$node\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "description": "This panel shows historical utilization for the node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "SUM(container_memory_usage_bytes{namespace!=\"\",instance=\"$node\"}) / SUM(kube_node_status_capacity_memory_bytes{node=\"$node\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=\"$node\"}) / sum(kube_node_status_capacity_memory_bytes{node=\"$node\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "description": "Traffic in and out of this namespace, as a sum of the pods within it",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "<- in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "-> out"
    }
   ]
  },
  {
   "title": "Current pods",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"\",container_name!=\"POD\",pod_name!=\"\",instance=\"$node\"}[10m])) by (pod_name)"
    },
    {
     "expr": "sum(label_replace(\nsum(avg_over_time(kube_pod_container_resource_requests_cpu_cores{container!=\"\",container!=\"POD\",node=\"$node\"}[10m])) by (pod), \n\"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)"
    },
    {
     "expr": "sum(avg_over_time(container_memory_usage_bytes{container_name!=\"\",container_name!=\"POD\",pod_name!=\"\",instance=\"$node\"}[10m])) by (pod_name)\n"
    },
    {
     "expr": "sum(label_replace(label_replace(\nsum(avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!=\"\",container!=\"POD\",node=\"$node\"}[10m])) by (pod),\n\"container_name\",\"$1\",\"container\",\"(.+)\"), \"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)\n"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "description": "Disk reads and writes for the namespace, as a sum of the pods within it",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_fs_writes_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "<- write"
    },
    {
     "expr": "- sum (rate (container_fs_reads_bytes_total{instance=\"$node\"}[10m]))",
     "legendFormat": "-> read"
    }
   ]
  }
 ]
}