{
 "title": "Sistema Noticias",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status do Micro Serciço",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_endpoint_ports{port_number=\"80\", endpoint=\"svc-sistema-noticias\"}"
    }
   ]
  },
  {
   "title": "Monitoramento Requisição HTTP - Portal Noticias",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate({app=\"sistema-noticias\"}[1m])"
    }
   ]
  },
  {
   "title": "Logs de  Requisição HTTP - Portal Noticias",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"sistema-noticias\"}"
    }
   ]
  }
 ]
}